package ru.lavafrai.maiapp.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val MaiColor = Color(0xff148fe6)
val MaiColorDark = Color(0xFF21325b)
val MaiColorLight = Color(0xFF7DCCFA)

val MarkGreenColor = Color(0xFF7fce51)
val MarkYellowColor = Color(0xFFc0d242)
val MarkOrangeColor = Color(0xFFf89f3c)
val MarkRedColor = Color(0xFFe4726a)
val MarkTextColor = Color(0xFFffffff)

val md_theme_light_primary = Color(0xFF006398)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCDE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D31)
val md_theme_light_secondary = Color(0xFF51606F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E4F6)
val md_theme_light_onSecondaryContainer = Color(0xFF0D1D2A)
val md_theme_light_tertiary = Color(0xFF00658B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72787E)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF93CCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006398)
val md_theme_light_outlineVariant = Color(0xFFC2C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF93CCFF)
val md_theme_dark_onPrimary = Color(0xFF003351)
val md_theme_dark_primaryContainer = Color(0xFF004B74)
val md_theme_dark_onPrimaryContainer = Color(0xFFCDE5FF)
val md_theme_dark_secondary = Color(0xFFB8C8DA)
val md_theme_dark_onSecondary = Color(0xFF23323F)
val md_theme_dark_secondaryContainer = Color(0xFF394857)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E4F6)
val md_theme_dark_tertiary = Color(0xFF7ED0FF)
val md_theme_dark_onTertiary = Color(0xFF00344A)
val md_theme_dark_tertiaryContainer = Color(0xFF004C6A)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CE)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF006398)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF93CCFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF008BD2)
